server:
  port: 8888

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/baonoob
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/identity/**
          filters:
            - StripPrefix=2

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
          filters:
            - StripPrefix=2

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
          filters:
            - StripPrefix=2

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/profile/**
          filters:
            - StripPrefix=2

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - StripPrefix=2

app:
  api-prefix: /api/v1
resilience4j.circuitbreaker:
  instances:
    identityServiceCircuit:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      minimumNumberOfCalls: 3
      failureRateThreshold: 50
      waitDurationInOpenState: 5000